package fr.loganbraga.hogwash.Error;

public enum ErrorKind {
	BASE_ERROR,
	BUILTINS_BOOTSTRAP,
	VAR_FORWARD_REF,
	VAR_NOT_FOUND,
	VAR_CALLED,
	VAR_ALREADY_DEF,
	FUNC_ALREADY_DEF,
	FUNC_NOT_FOUND,
	FUNC_AS_VAR,
	PARAM_NAME_TAKEN,
	FUNC_NEVER_CALLED,
	VAR_NEVER_USED,
	EXT_FUNC_DEF,
	REDUNDANT_IMPORT,
	MODULE_NOT_FOUND,
	CONST_NOT_SET,
	CONST_SET,
	LOOP_ST_NO_LOOP,
	VAR_NEVER_SET
}
